/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomIdRouteImport } from './routes/room/$roomId'
import { Route as MeetSidepanelRouteImport } from './routes/meet/sidepanel'
import { Route as RoomWsRoomIdRouteImport } from './routes/room/ws/$roomId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetSidepanelRoute = MeetSidepanelRouteImport.update({
  id: '/meet/sidepanel',
  path: '/meet/sidepanel',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomWsRoomIdRoute = RoomWsRoomIdRouteImport.update({
  id: '/room/ws/$roomId',
  path: '/room/ws/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/meet/sidepanel': typeof MeetSidepanelRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/room/ws/$roomId': typeof RoomWsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/meet/sidepanel': typeof MeetSidepanelRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/room/ws/$roomId': typeof RoomWsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/meet/sidepanel': typeof MeetSidepanelRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/room/ws/$roomId': typeof RoomWsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/meet/sidepanel'
    | '/room/$roomId'
    | '/api/auth/$'
    | '/room/ws/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/meet/sidepanel'
    | '/room/$roomId'
    | '/api/auth/$'
    | '/room/ws/$roomId'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/meet/sidepanel'
    | '/room/$roomId'
    | '/api/auth/$'
    | '/room/ws/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  MeetSidepanelRoute: typeof MeetSidepanelRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  RoomWsRoomIdRoute: typeof RoomWsRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet/sidepanel': {
      id: '/meet/sidepanel'
      path: '/meet/sidepanel'
      fullPath: '/meet/sidepanel'
      preLoaderRoute: typeof MeetSidepanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/ws/$roomId': {
      id: '/room/ws/$roomId'
      path: '/room/ws/$roomId'
      fullPath: '/room/ws/$roomId'
      preLoaderRoute: typeof RoomWsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  MeetSidepanelRoute: MeetSidepanelRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  RoomWsRoomIdRoute: RoomWsRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
